languageCode = "en-us"
title = "The Tahiti Surf Bible"
baseURL = "https://The-Tahiti-Surf-Bible.jerad.xyz"
theme = "../themes/hugo-theme-dopetrope"

[params.portfolio]
    title = "My Portfolio"
    foldername = "portfolio"
    findoutmoretext = "Find out more"

[params.blog]
    title = "The Blog"
    viewalltext = "View All"
    foldername = "blog"

[params.settings]
    googleanalytics = ""
    disqus = ""